# Cloud Build - equilaw
# Project: geminihackathon0228
# Deploys to Cloud Run (Seoul region)

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "asia-northeast3-docker.pkg.dev/${PROJECT_ID}/equilaw/equilaw:latest"
      - "."
    id: build

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "asia-northeast3-docker.pkg.dev/${PROJECT_ID}/equilaw/equilaw"
    id: push
    waitFor: [build]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "equilaw"
      - "--image=asia-northeast3-docker.pkg.dev/${PROJECT_ID}/equilaw/equilaw:latest"
      - "--region=asia-northeast3"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=8080"
      - "--memory=1Gi"
      - "--cpu=1"
      - "--min-instances=0"
      - "--max-instances=10"
    id: deploy
    waitFor: [push]

images:
  - "asia-northeast3-docker.pkg.dev/${PROJECT_ID}/equilaw/equilaw:latest"

options:
  logging: CLOUD_LOGGING_ONLY
